openapi: 3.0.0
info:
  version: ""
  title: socks 
  description: socks resources
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
paths:
  "/socks/{customerId}":
    get:
      description: ""
      operationId: Get socks
      parameters:
        - name: customerId
          in: path
          required: true
          example: "1"
          schema:
            type: string
      responses:
        "200":
          description: Returns socks
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/Getsocksresponse"
    delete:
      description: ""
      operationId: Delete socks
      parameters:
        - name: customerId
          in: path
          required: true
          example: "1"
          schema:
            type: string
      responses:
        "202":
          description: ""
  "/socks/{customerId}/items":
    post:
      description: ""
      operationId: Add an item to the socks
      parameters:
        - name: customerId
          in: path
          required: true
          example: 579f21ae98684924944651bf
          schema:
            type: string
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/SocksItem"
          text/plain:
            schema:
              $ref: "#/components/schemas/SocksItem"
        required: true
      responses:
        "201":
          description: ""
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/SocksItem"
    patch:
      description: Update an item
      operationId: Update item
      parameters:
        - name: customerId
          in: path
          required: true
          example: 579f21ae98684924944651bf
          schema:
            type: string
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              type: object
          text/plain:
            schema:
              type: object
        required: true
      responses:
        "200":
          description: ""
  "/socks/{customerId}/items/{itemId}":
    delete:
      description: Delete socks item
      operationId: delete
      parameters:
        - name: itemId
          in: path
          required: true
          example: 819e1fbf-8b7e-4f6d-811f-693534916a8b
          schema:
            type: string
        - name: customerId
          in: path
          required: true
          example: 579f21ae98684924944651bf
          schema:
            type: string
      responses:
        "202":
          description: Delete response
servers:
  - url: http://socks/
components:
  schemas:
    Getsocksresponse:
      title: Get socks response
      type: object
      properties:
        customerId:
          type: string
      required:
        - customerId
    SocksItem:
      title: Socks item
      type: object
      properties:
        itemId:
          type: string
        quantity:
          type: integer
        unitPrice:
          type: number
      required:
        - itemId
        - quantity
        - unitPrice
